version: '2.2'
services:
  tagdemo-mysql:
    image: tagdemo/mysql
    container_name: tagdemo-mysql
    env_file:
      - newrelic.env

  tagdemo-api:
    image: tagdemo/api-server
    container_name: api-server
    ports:
      - "8080:8080"
    depends_on:
      - tagdemo-mysql
      - tagdemo-nats
    env_file:
      - newrelic.env
  
  tagdemo-nats:
    image: nats
    container_name: nats-server

  tagdemo-wordpress:
    image: tagdemo/wordpress
    container_name: tagdemo-wordpress
    links:
      - "tagdemo-mysql:mysql"
    ports:
      - "3000:80"
    depends_on:
      - tagdemo-mysql
    env_file:
      - newrelic.env
