version: '2.2'
services:
  tagdemo-db:
    image: tagdemo/mysql
    container_name: tagdemo-mysql
    env_file:
        - newrelic.env

  tagdemo-api:
    image: tagdemo/api-server
    container_name: api-server
    ports:
     - "8080:8080"
    depends_on:
      - tagdemo-db
      - tagdemo-nats
    env_file:
        - newrelic.env
  
  tagdemo-nats:
    image: nats
    container_name: nats-server
