version: '2.2'
services:
  tagdemo-db:
    image: tagdemo/mysql
    container_name: tagdemo-mysql
    build: ./mysql
    ports:
     - "3306:3306"
  
  tagdemo-nats:
    image: nats
    container_name: nats-server
    ports:
     - "4222:4222"
  
