version: '2.2'
services:
  tagdemo-db:
    image: tagdemo/mysql
    container_name: tagdemo-mysql
    build: ./data
    expose:
     - "3306"

  tagdemo-api:
    image: tagdemo/api-server
    container_name: api-server
    build: ./api-server
    ports:
     - "8080:8080"
    depends_on:
      - tagdemo-db
      - tagdemo-nats
  
  tagdemo-nats:
    image: nats
    container_name: nats-server
    ports:
     - "4222:4222"
  
